%% Surface profiling function+ finding the holes
function [centers,radii,depth,dorsal_surface,im]=S_H_detect_C(sens,vol)
%Finding the latest folder generated by Lumedica
%%%-----------------  Surface detecton + cleaning ---------------%%%
%[gr,~,~]=imgradient3(vol);
[~,gr,~]=gradient(vol);
[~,dorsal_surface]=max(gr,[],1);
dorsal_surface=squeeze(dorsal_surface);
%  Smoothing the surface
dorsal_surface=medfilt2(dorsal_surface,[15 15],'symmetric');
% Adjust the orientation
%dorsal_surface_c=512-dorsal_surface;
dorsal_surface=512-flip(flip(dorsal_surface),2);
dorsal_surface=dorsal_surface';
%
% dorsal_surface(dorsal_surface==511)=nan;
% %%
% volumeViewer(vol)
% volumeViewer(Vol)
%
%%%------------- Finding the holes----------------
% holder=dorsal_surface;
% 
% dorsal_surface=holder;
Cval=mean(dorsal_surface(200:300,200:300),'all');
dorsal_surface(dorsal_surface>(Cval+511)/2.2)=nan;
% avr=mean(dorsal_surface,'all','omitnan');
dorsal_surface(isnan(dorsal_surface))=Cval;
% Show the target from the top
%  rect=[120,80,300,300];
% %[J,rect] = imcrop(dorsal_surface);
% im2=imcrop(dorsal_surface,rect);
% Show the target from the top
im=mat2gray(dorsal_surface);
figure;
imshow(im)
title('First draw a line that is the diameter of the anticipated circles')
% Find the expected diameter of the disks by drawing the diameter of one of them in the image
d = drawline;
pos = d.Position;
diffPos = diff(pos);
diameter=hypot(diffPos(1),diffPos(2));
radious=floor(diameter/2);
var=floor(radious/2);
% Find the circles increased sensitivity finding dark disks:
[centers,radii]=imfindcircles(im,[radious-var radious+var],"ObjectPolarity","dark","Sensitivity",sens);
close all
figure
imshow(im)
title('If any hole is not detected, click on their center. Otherwise just press enter')
h = viscircles(centers,radii,'LineWidth',0.4);
% Sort the centers
% centers=sortrows(centers,1); % right to left
% centers=sortrows(centers,2); % sort centers top to bottom
% save('Detected_circles5.mat','centers','radii'); 
% add their depth to them
[X,Y]=getpts;
L=length(centers);
for k=1:length(X)
%cc(l,:)= [X(l) Y(l)] 
centers(L+k,:)=[X(k) Y(k)]; 
radii(L+k,:)=radious;
end
viscircles(centers(L+1:end,:),radii(L+1:end,:),'LineWidth',0.4);

centers=sortrows(centers,1); % right to left
centers=sortrows(centers,2); % sort centers top to bottom

% add their depth to them
[rows,cols,~] = size(dorsal_surface);
[R,C] = ndgrid(1:rows, 1:cols);

for i=1:length(centers)
    circle_radius=radii(i);
    % Make a mask that only includes inside the identified circle
    mask=(R-centers(i,2)).^2 + (C-centers(i,1)).^2 < circle_radius.^2 ;
    intensities_inside_circle = dorsal_surface(mask);
    depth(i) = min(intensities_inside_circle);
end
% name=latestfile;
end